
const REVIEWS_PER_PAGE = 6;
const reviews = [
{"id":1,"title":"AeroMax Noise-Canceling Headphones","category":"electronics","rating":4.6,"price":"$129","summary":"The AeroMax delivers strong active noise cancellation, long battery life and comfortably padded earcups. Great for commuting and long listening sessions.","pros":["Excellent ANC","Comfortable fit","Good battery life"],"cons":["Slightly heavy","Not the cheapest"],"affiliate":"https://example.com/product/aeromax?aff=affiliate123"},
{"id":2,"title":"HomeBrew Espresso Machine Pro","category":"home","rating":4.2,"price":"$349","summary":"A semi-automatic machine that brings café-quality espresso to your kitchen with precise temperature control and a reliable steam wand.","pros":["Stable temp","Good steam power","Durable build"],"cons":["Learning curve","Large footprint"],"affiliate":"https://example.com/product/homebrew-espresso?aff=affiliate123"},
{"id":3,"title":"TrailMate 3-Season Tent","category":"outdoor","rating":4.4,"price":"$199","summary":"Lightweight and quick to pitch, the TrailMate keeps you dry in moderate weather and packs down small for backpacking trips.","pros":["Lightweight","Quick setup","Good ventilation"],"cons":["Limited space for gear","Not for extreme weather"],"affiliate":"https://example.com/product/trailmate-tent?aff=affiliate123"},
{"id":4,"title":"BrightHome Smart Bulb Kit","category":"home","rating":4.0,"price":"$59","summary":"Simple to integrate with voice assistants and offers widespread color presets. Good value for mood lighting and smart automations.","pros":["Easy setup","Good color range","Affordable"],"cons":["App could be improved","Some flicker at low brightness"],"affiliate":"https://example.com/product/brighthome-bulb?aff=affiliate123"},
{"id":5,"title":"FlexGrip Adjustable Dumbbells","category":"home","rating":4.3,"price":"$259","summary":"A compact alternative to stacked dumbbells with fast adjustment and solid build quality. Ideal for small home gyms.","pros":["Space-saving","Smooth adjustment","Solid construction"],"cons":["Expensive initial cost","Plastic components"],"affiliate":"https://example.com/product/flexgrip-dumbbells?aff=affiliate123"},
{"id":6,"title":"PixelSharp 27\" 4K Monitor","category":"electronics","rating":4.5,"price":"$429","summary":"Crisp 4K resolution and strong color reproduction for creators and productivity users. Includes USB-C with power delivery.","pros":["Crisp image","USB-C PD","Good color"],"cons":["No HDR true peak","Stand is basic"],"affiliate":"https://example.com/product/pixelsharp-4k?aff=affiliate123"},
{"id":7,"title":"EcoFlow Portable Power Station","category":"electronics","rating":4.1,"price":"$499","summary":"A reliable portable power station for camping and emergency backup with multiple output ports and fast recharge options.","pros":["Multiple ports","Fast recharge","Portable"],"cons":["Heavy","Pricey at high capacity"],"affiliate":"https://example.com/product/ecoflow-power?aff=affiliate123"},
{"id":8,"title":"GardenGuard Robotic Mower","category":"outdoor","rating":3.9,"price":"$799","summary":"Automates weekly lawn maintenance with programmable zones. Works well on moderate lawns but struggles on extremely steep inclines.","pros":["Automates chore","Programmable","Quiet"],"cons":["Expensive","Complex boundary setup"],"affiliate":"https://example.com/product/gardenguard-mower?aff=affiliate123"},
{"id":9,"title":"SwiftNote Productivity App","category":"software","rating":4.7,"price":"Free/$4.99/mo","summary":"A focused note-taking and task manager with markdown support and powerful search. Syncs across devices securely.","pros":["Fast search","Markdown support","Cross-device sync"],"cons":["Advanced features behind paywall"],"affiliate":"https://example.com/product/swiftnote?aff=affiliate123"},
{"id":10,"title":"AquaPure Water Filter Pitcher","category":"home","rating":4.0,"price":"$39","summary":"Simple pitcher that improves taste and reduces chlorine and sediment. Replacement filters available at moderate cost.","pros":["Improves taste","Affordable","Easy to use"],"cons":["Filter replacements add up"],"affiliate":"https://example.com/product/aquapure-pitcher?aff=affiliate123"},
{"id":11,"title":"ComfyCloud Ergonomic Chair","category":"home","rating":4.4,"price":"$299","summary":"Provides excellent lumbar support and breathable mesh for long hours of sitting. Easy assembly and adjustable settings.","pros":["Great lumbar support","Breathable mesh","Adjustable"],"cons":["Arm pads wear over time"],"affiliate":"https://example.com/product/comfycloud-chair?aff=affiliate123"},
{"id":12,"title":"SoundLoom Bluetooth Speaker","category":"electronics","rating":4.2,"price":"$149","summary":"Portable speaker with punchy bass and IPX7 water resistance. Good battery life and companion app for EQ adjustments.","pros":["Good bass","Water resistant","Long battery"],"cons":["Slight distortion at max volume"],"affiliate":"https://example.com/product/soundloom-speaker?aff=affiliate123"},
{"id":13,"title":"CookMate Multi-Cooker","category":"home","rating":4.5,"price":"$119","summary":"Versatile multi-cooker that replaces several appliances. Reliable presets and easy cleanup with dishwasher-safe parts.","pros":["Versatile","Easy cleanup","Protected presets"],"cons":["Takes time to master settings"],"affiliate":"https://example.com/product/cookmate-multi?aff=affiliate123"},
{"id":14,"title":"NomadLight Headlamp","category":"outdoor","rating":4.3,"price":"$39","summary":"Small, bright and comfortable headlamp with multiple beam patterns. Great for trail runs and camping chores after dark.","pros":["Lightweight","Multiple beams","Good battery"],"cons":["Plastic strap hardware"],"affiliate":"https://example.com/product/nomadlight-headlamp?aff=affiliate123"},
{"id":15,"title":"SecureKey Password Manager","category":"software","rating":4.6,"price":"Free/$2.99/mo","summary":"Strong password management with secure vault and browser integration. Easy sharing for families and teams.","pros":["Strong security","Cross-platform","Family sharing"],"cons":["Learning curve for advanced features"],"affiliate":"https://example.com/product/securekey?aff=affiliate123"},
{"id":16,"title":"UrbanRide Electric Scooter","category":"outdoor","rating":3.8,"price":"$549","summary":"Compact scooter with decent range for commuting. Notable for its portability but limited top speed over long hills.","pros":["Portable","Good range for city","Foldable"],"cons":["Limited hill performance","Ride comfort on rough pavement"],"affiliate":"https://example.com/product/urbanride-scooter?aff=affiliate123"},
{"id":17,"title":"PureSound Earbuds Pro","category":"electronics","rating":4.4,"price":"$179","summary":"True wireless earbuds with balanced sound and adaptive noise cancellation. Comfortable tip selection helps fit and seal.","pros":["Adaptive ANC","Good sound balance","Comfortable"],"cons":["Case could be smaller"],"affiliate":"https://example.com/product/puresound-earbuds?aff=affiliate123"},
{"id":18,"title":"ChillMate Portable AC","category":"home","rating":3.7,"price":"$229","summary":"Provides spot cooling and is handy in rooms without central AC. Works best in small spaces and tends to be noisy on high settings.","pros":["Portable spot cooling","Easy setup"],"cons":["Noisy at high speed","Limited to small rooms"],"affiliate":"https://example.com/product/chillmate-ac?aff=affiliate123"},
{"id":19,"title":"VeloTrack GPS Bike Computer","category":"outdoor","rating":4.1,"price":"$249","summary":"Accurate GPS tracking with long battery life and easy-to-follow maps. Mounting system is secure and the screen is readable in sunlight.","pros":["Accurate GPS","Readable screen","Long battery"],"cons":["Expensive accessories"],"affiliate":"https://example.com/product/velotrack-gps?aff=affiliate123"},
{"id":20,"title":"StudioLight Softbox Kit","category":"electronics","rating":4.5,"price":"$149","summary":"Professional softbox kit for streaming and video content creation. Durable stands and consistent color temperature deliver high-quality lighting.","pros":["Consistent color","Sturdy stands","Great for creators"],"cons":["Bulky case for transport"],"affiliate":"https://example.com/product/studiolight-kit?aff=affiliate123"},
{"id":21,"title":"FitPulse Fitness Tracker","category":"electronics","rating":4.0,"price":"$99","summary":"A reliable fitness tracker for daily metrics including sleep tracking and heart rate. Battery life is competitive in its class.","pros":["Accurate heart rate","Sleep tracking","Affordable"],"cons":["App UI can be confusing"],"affiliate":"https://example.com/product/fitpulse-tracker?aff=affiliate123"},
{"id":22,"title":"GreenThumb Indoor Planter","category":"home","rating":4.3,"price":"$69","summary":"Self-watering planter that helps keep plants healthy with minimal fuss. Clean design fits modern interiors and reduces maintenance.","pros":["Self-watering","Modern design","Reduces watering errors"],"cons":["A bit small for large plants"],"affiliate":"https://example.com/product/greenthumb-planter?aff=affiliate123"},
{"id":23,"title":"CloudGuard VPN Pro","category":"software","rating":4.4,"price":"$3.99/mo","summary":"Fast, privacy-focused VPN with easy apps for all major platforms and robust server coverage. Strong encryption and no-logs policy.","pros":["Fast servers","No-logs policy","Easy apps"],"cons":["Occasional location inconsistency"],"affiliate":"https://example.com/product/cloudguard-vpn?aff=affiliate123"},
{"id":24,"title":"Chef'sEdge Knife Set","category":"home","rating":4.6,"price":"$199","summary":"High-quality stainless steel knives with excellent balance and sharp factory edge. Comes with a protective block and maintenance tips.","pros":["Sharp out of box","Well-balanced","Durable"],"cons":["Requires careful hand washing"],"affiliate":"https://example.com/product/chefsedge-knives?aff=affiliate123"},
{"id":25,"title":"SkyCam 4K Drone","category":"electronics","rating":4.0,"price":"$899","summary":"Stable 4K aerial footage and intelligent flight modes make it a great option for hobbyists and prosumers. Battery life is average for the class.","pros":["4K footage","Stable gimbal","Smart modes"],"cons":["Battery life average","Expensive repairs"],"affiliate":"https://example.com/product/skycam-drone?aff=affiliate123"},
{"id":26,"title":"NomadTrail Hiking Boots","category":"outdoor","rating":4.5,"price":"$139","summary":"Comfortable, waterproof hiking boots that break in quickly and provide solid traction on varied terrain. Great for long day hikes.","pros":["Waterproof","Comfortable fit","Good traction"],"cons":["Slightly heavy"],"affiliate":"https://example.com/product/nomadtrail-boots?aff=affiliate123"},
{"id":27,"title":"OfficeMate Standing Desk","category":"home","rating":4.2,"price":"$499","summary":"Electric height-adjustable desk with stable lifting columns and memory presets. Sturdy surface and easy assembly instructions.","pros":["Stable","Memory presets","Easy assembly"],"cons":["Assembly takes time"],"affiliate":"https://example.com/product/officemate-desk?aff=affiliate123"},
{"id":28,"title":"BrightCam Security Camera","category":"electronics","rating":4.1,"price":"$129","summary":"An affordable security camera with night vision and motion alerts. Local recording options are available alongside cloud plans.","pros":["Night vision","Motion alerts","Affordable"],"cons":["Cloud plans cost extra"],"affiliate":"https://example.com/product/brightcam-camera?aff=affiliate123"},
{"id":29,"title":"BrewMaster Kettle","category":"home","rating":4.4,"price":"$89","summary":"Precision electric kettle with temperature presets for different teas and coffees. Quick boil time and a helpful hold-temp feature.","pros":["Temperature presets","Quick boil","Hold-temp feature"],"cons":["Corded base limits placement"],"affiliate":"https://example.com/product/brewmaster-kettle?aff=affiliate123"},
{"id":30,"title":"ZenNoise Sleep Machine","category":"home","rating":3.9,"price":"$49","summary":"Generates a variety of soothing white noise and nature sounds. Small footprint and easy controls but sound quality is mid-tier.","pros":["Multiple sounds","Compact","Easy controls"],"cons":["Audio fidelity could be better"],"affiliate":"https://example.com/product/zenn

oise-sleep?aff=affiliate123"}];
function safeText(str){return String(str).replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function renderRating(r){const fullStars=Math.floor(r);const half=(r-fullStars)>=0.5;let out="";for(let i=0;i<fullStars;i++){out+='<span class="star">★</span>'}if(half){out+='<span class="star">☆</span>'}const rem=5-fullStars-(half?1:0);for(let i=0;i<rem;i++){out+='<span class="star" style="opacity:0.15">★</span>'}return out}
function createReviewCard(review){const card=document.createElement("article");card.className="review-card";card.setAttribute("data-id",review.id);card.setAttribute("data-category",review.category);const header=document.createElement("div");header.className="review-header";const left=document.createElement("div");const title=document.createElement("h3");title.className="title";title.innerHTML=safeText(review.title);left.appendChild(title);const meta=document.createElement("div");meta.className="meta";meta.innerHTML=`<span class="kicker">${safeText(review.category)}</span> • <span class="badge">Reviewed</span>`;left.appendChild(meta);header.appendChild(left);const right=document.createElement("div");right.innerHTML=`<div class="rating" title="${review.rating} stars"><span class="rating-stars">${renderRating(review.rating)}</span><span class="clicks">${getClicks(review.id)} clicks</span></div>`;header.appendChild(right);card.appendChild(header);const body=document.createElement("div");body.className="card-body";const summary=document.createElement("div");summary.className="summary";summary.innerHTML=`<p>${safeText(review.summary)}</p><p><strong>Quick take:</strong> ${Math.round(review.rating*20)}% match for general users based on testing.</p>`;body.appendChild(summary);const aside=document.createElement("div");aside.className="aside-cta";aside.innerHTML=`<div class="price">${safeText(review.price)}</div><ul class="pros"><li>${safeText(review.pros[0]||"Benefit")}</li><li>${safeText(review.pros[1]||"Benefit")}</li><li>${safeText(review.pros[2]||"Benefit")}</li></ul><ul class="cons"><li>${safeText(review.cons[0]||"Drawback")}</li><li>${safeText(review.cons[1]||"Drawback")}</li></ul><div class="affiliate"><a href="${review.affiliate}" data-id="${review.id}" target="_blank" rel="noopener sponsored">Buy / Learn</a><button class="btn copy" data-clipboard="${review.affiliate}" aria-label="Copy affiliate link">Copy</button></div>`;body.appendChild(aside);card.appendChild(body);const footer=document.createElement("div");footer.className="card-footer";footer.innerHTML=`<div class="meta">ID: ${review.id} • <button class="btn small share" data-id="${review.id}">Share</button><button class="btn small details" data-id="${review.id}">More</button></div>`;card.appendChild(footer);return card}
function getClicks(id){const key=`clicks_${id}`;const val=localStorage.getItem(key);return val?Number(val):0}
function incrementClicks(id){const key=`clicks_${id}`;const val=getClicks(id)+1;localStorage.setItem(key,String(val));updateClicksDisplay(id)}
function updateClicksDisplay(id){const el=document.querySelector(`.review-card[data-id="${id}"] .clicks`);if(el)el.textContent=`${getClicks(id)} clicks`}
function renderReviews(list,page=1,perPage=REVIEWS_PER_PAGE){const container=document.getElementById("reviewsList");container.innerHTML="";const start=(page-1)*perPage;const pageItems=list.slice(start,start+perPage);if(pageItems.length===0){container.innerHTML='<div class="widget"><p class="muted">No reviews match your search or filters.</p></div>';return}pageItems.forEach(r=>container.appendChild(createReviewCard(r)));attachCardEvents()}
function attachCardEvents(){document.querySelectorAll(".review-card a").forEach(a=>{a.addEventListener("click",e=>{const id=Number(a.getAttribute("data-id"));incrementClicks(id)})});document.querySelectorAll(".review-card .copy").forEach(btn=>{btn.addEventListener("click",e=>{const clip=btn.getAttribute("data-clipboard");navigator.clipboard.writeText(clip).then(()=>{btn.textContent="Copied";setTimeout(()=>{btn.textContent="Copy"},1200)})})});document.querySelectorAll(".review-card .share").forEach(btn=>{btn.addEventListener("click",e=>{const id=btn.getAttribute("data-id");const review=reviews.find(r=>String(r.id)===String(id));if(!review)return;const shareText=`${review.title} — ${review.summary} Buy: ${review.affiliate}`;if(navigator.share){navigator.share({title:review.title,text:review.summary,url:review.affiliate}).catch(()=>{copyFallback(shareText)})}else{copyFallback(shareText);alert('Link copied to clipboard for sharing')}})});document.querySelectorAll(".review-card .details").forEach(btn=>{btn.addEventListener("click",e=>{const id=btn.getAttribute("data-id");showDetails(id)})})}
function copyFallback(text){navigator.clipboard.writeText(text).then(()=>{})}
function showDetails(id){const review=reviews.find(r=>String(r.id)===String(id));if(!review){alert("Review not found");return}const details=`${review.title}\n\nCategory: ${review.category}\nRating: ${review.rating}\nPrice: ${review.price}\n\nSummary:\n${review.summary}\n\nPros:\n- ${review.pros.join("\n- ")}\n\nCons:\n- ${review.cons.join("\n- ")}\n\nAffiliate link:\n${review.affiliate}`;alert(details)}
function applyFiltersAndSort(){const q=document.getElementById("search").value.trim().toLowerCase();const minRating=Number(document.getElementById("minRating").value);const sort=document.getElementById("sort").value;let list=reviews.filter(r=>{const matchCategory=true;const hay=(r.title+" "+r.summary+" "+r.category+" "+r.pros.join(" ")+" "+r.cons.join(" ")).toLowerCase();const matchQuery=q===""||hay.indexOf(q)!==-1;const matchRating=r.rating>=minRating;return matchCategory&&matchQuery&&matchRating});if(sort==="rating-desc"){list.sort((a,b)=>b.rating-a.rating)}else if(sort==="rating-asc"){list.sort((a,b)=>a.rating-b.rating)}else if(sort==="popular"){list.sort((a,b)=>getClicks(b.id)-getClicks(a.id))}else if(sort==="newest"){list.sort((a,b)=>b.id-a.id)}renderReviews(list,1);currentList=list;currentPage=1;updatePageInfo()}
let currentPage=1;let currentList=[...reviews];function updatePageInfo(){const info=document.getElementById("pageInfo");const total=Math.max(1,Math.ceil(currentList.length/REVIEWS_PER_PAGE));info.textContent=`Page ${currentPage} of ${total}`}function goToPage(page){const total=Math.max(1,Math.ceil(currentList.length/REVIEWS_PER_PAGE));if(page<1)page=1;if(page>total)page=total;currentPage=page;renderReviews(currentList,currentPage);updatePageInfo()}
document.getElementById("search").addEventListener("input",()=>{applyFiltersAndSort()});document.getElementById("sort").addEventListener("change",()=>{applyFiltersAndSort()});document.getElementById("minRating").addEventListener("change",()=>{applyFiltersAndSort()});document.querySelectorAll(".filter-btn").forEach(btn=>{btn.addEventListener("click",e=>{const cat=btn.getAttribute("data-cat");document.getElementById("search").value="";if(cat==="all"){currentList=[...reviews]}else{currentList=reviews.filter(r=>r.category===cat)}currentPage=1;renderReviews(currentList,currentPage);updatePageInfo()})});document.getElementById("prevPage").addEventListener("click",()=>{goToPage(currentPage-1)});document.getElementById("nextPage").addEventListener("click",()=>{goToPage(currentPage+1)})
document.getElementById("themeToggle").addEventListener("click",()=>{const body=document.body;const isLight=body.classList.toggle("theme-light");document.getElementById("themeToggle").setAttribute("aria-pressed",String(isLight));localStorage.setItem("themeLight",isLight? "1":"0")})
function initTheme(){const saved=localStorage.getItem("themeLight");if(saved==="1"){document.body.classList.add("theme-light");document.getElementById("themeToggle").setAttribute("aria-pressed","true")}}function init(){initTheme();currentList=[...reviews];renderReviews(currentList,1);updatePageInfo();document.getElementById("exportCsv").addEventListener("click",e=>{e.preventDefault();exportTopClicksAsCsv()})}
function exportTopClicksAsCsv(){const data=reviews.map(r=>({id:r.id,title:r.title,clicks:getClicks(r.id),affiliate:r.affiliate})).sort((a,b)=>b.clicks-a.clicks).slice(0,50);const rows=[["id","title","clicks","affiliate"]];data.forEach(d=>rows.push([d.id,`"${d.title.replace(/"/g,'""')}"`,d.clicks,`"${d.affiliate}"`]));const csv=rows.map(r=>r.join(",")).join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8;"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="top-clicks.csv";document.body.appendChild(link);link.click();link.remove()}
function hydrateClicksSample(){let any=false;for(let i=0;i<reviews.length;i++){const k=`clicks_${reviews[i].id}`;if(!localStorage.getItem(k)){localStorage.setItem(k,String(Math.floor(Math.random()*45)));any=true}}if(any)console.info("Click counters initialized for demo purposes.")}hydrateClicksSample();init()
